language: python
python:
  - "2.6"
  - "2.7"
install:
  - python setup.py install
  - pip install -r requirements-dev.txt
  - pip install python-coveralls
script:
  - ./test.sh
after_success:
  - coveralls